# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-12 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dgs', '0003_contestant_current_handicap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='current_handicap',
        ),
        migrations.AlterField(
            model_name='contestant',
            name='initial_handicap',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
